name: Build Fluxcraft WASM

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force a new build and overwrite cache

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - uses: actions/cache@v5
        id: cache-rust-build
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            fluxcraft-rs/target
            fluxcraft-rs/crates/fluxcraft-wasm/pkg
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/*.rs') }}

      - name: Early exit if cache hit and not forced
        if: steps.cache-rust-build.outputs.cache-hit == 'true' && github.event.inputs.force != 'true'
        run: |
          echo "Cache hit and force=false. Skipping build."
          exit 0

      # -------------------------
      # Rust / WASM build
      # -------------------------
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build rust binary
        working-directory: fluxcraft-rs
        run: cargo build --release

      - name: Install wasm-pack
        run: cargo install wasm-pack

      - name: Build FluxCraft WASM package
        working-directory: fluxcraft-rs/crates/fluxcraft-wasm
        env:
          RUSTFLAGS: --cfg getrandom_backend="wasm_js"
        run: wasm-pack build --release --target bundler
